# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - Chatproject

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - '**.html'
      - '**.css'
      - '**.js'
      - 'requirements.txt'
      - '.env'
      - 'static/**'
      - 'templates/**'
      - '!**.md'
      - '!.gitignore'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unixodbc-dev
          pip install --upgrade pip
          pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      
      - name: Check for deployment changes
        id: check_changes
        run: |
          # List of files that require deployment when changed
          DEPLOY_PATTERNS=("*.py" "*.html" "*.css" "*.js" "requirements.txt" ".env" "static/*" "templates/*")
          CHANGES_DETECTED=false
          
          for pattern in "${DEPLOY_PATTERNS[@]}"; do
            if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "$pattern"; then
              CHANGES_DETECTED=true
              break
            fi
          done
          
          echo "changes_detected=$CHANGES_DETECTED" >> $GITHUB_OUTPUT

      - name: Zip artifact for deployment
        if: steps.check_changes.outputs.changes_detected == 'true'
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment jobs
        if: steps.check_changes.outputs.changes_detected == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: needs.build.outputs.changes_detected == 'true'
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3E27A70AB0824AB2A3779C2E0F8DF380 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AAB4AA58D5D9467D8095539E68C4D791 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_991897CBB01943799A0C155073FF4306 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'Chatproject'
          publish-profile: ${{ secrets.AZUREWEBAPP_PUBLISHPROFILE_E0F0F0F0E0F0F0F0E0F0F0F0E0F0F0F0 }}
          package: .
      